# Generated by Django 5.1.6 on 2025-05-23 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorie',
            },
        ),
        migrations.CreateModel(
            name='Producent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('kraj', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Producent',
                'verbose_name_plural': 'Producenci',
            },
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('opis', models.TextField()),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dostepnosc', models.BooleanField(default=True)),
                ('zdjecie', models.ImageField(blank=True, null=True, upload_to='produkty/')),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Czujniki.kategoria')),
                ('producent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Czujniki.producent')),
            ],
            options={
                'verbose_name': 'Produkt',
                'verbose_name_plural': 'Produkty',
            },
        ),
        migrations.CreateModel(
            name='Zamowienie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('nowe', 'Nowe'), ('zrealizowane', 'Zrealizowane'), ('anulowane', 'Anulowane')], default='nowe', max_length=20)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('produkty', models.ManyToManyField(to='Czujniki.produkt')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
