# Generated by Django 5.1.6 on 2025-03-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Czujnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('napiecieZasilania', models.PositiveSmallIntegerField()),
                ('rodzajZasilania', models.CharField(max_length=100)),
                ('opis', models.TextField(default='')),
                ('cena', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
            ],
        ),
    ]
