# Generated by Django 5.1.6 on 2025-05-23 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Czujniki', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zamowienie',
            options={'verbose_name': 'Zamówienie', 'verbose_name_plural': 'Zamówienia'},
        ),
    ]
