# Generated by Django 5.1.6 on 2025-03-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Czujniki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='czujnik',
            name='nazwa',
            field=models.CharField(default='', max_length=100),
        ),
    ]
